### ISSUE TITLE
有安装教程吗

### ISSUE THREAD

**Issue by atk-admin** [Clouditera/secgpt#1]

**Comment by boy-hack** [comment]
直接使用的话直接 `pytho webdemo.py --base_model w8ay/secgpt` 就行，保持网络通畅，会自动下载模型

**Comment by caojinghuan** [comment]
我运行了上述命令，出来下面这个报错。（自动下载了tokenizer_config.json，tokenization_baichuan.py）
import sentencepiece as spm
ModuleNotFoundError: No module named 'sentencepiece'

**Comment by wuheuu** [comment]
@caojinghuan `pip3.7 install sentencepiece`
