### ISSUE TITLE
页面加载不出来

### ISSUE THREAD

**Issue by 1120161807** [Clouditera/secgpt#11]
您好，请问仅运行python webdemo.py --base_model w8ay/secgpt需要将huggingface和wisemodel都下载下来吗？
 我运行时出现“网址为 http://0.0.0.0:7860/ 的网页可能暂时无法连接，或者它已永久性地移动到了新网址。”
谢谢！

**Comment by wuheuu** [comment]
@1120161807 huggingface和wisemodel是模型存放的网站，在哪个网站下载模型应该都是可以的，运行这个代码会自动下载模型。至于http://0.0.0.0:7860，这个是不是代理运行的端口？

**Comment by boy-hack** [comment]
> 您好，请问仅运行python webdemo.py --base_model w8ay/secgpt需要将huggingface和wisemodel都下载下来吗？ 我运行时出现“网址为 http://0.0.0.0:7860/ 的网页可能暂时无法连接，或者它已永久性地移动到了新网址。” 谢谢！

访问 http://127.0.0.1:7860
