### ISSUE TITLE
模型初始化

### ISSUE THREAD

**Issue by childlong** [Clouditera/secgpt#13]
模型初始化的时候没用使用config参数
config = transformers.AutoConfig.from_pretrained(
        pre_train_path,
        trust_remote_code=True,
    )
    config.use_cache = False
    model = AutoModelForCausalLM.from_pretrained(pre_train_path, trust_remote_code=True, device_map="auto")
是不是应该是这样的
config = transformers.AutoConfig.from_pretrained(
        pre_train_path,
        trust_remote_code=True,
    )
    config.use_cache = False
    model = AutoModelForCausalLM.from_pretrained(pre_train_path, config=config, trust_remote_code=True, device_map="auto")

**Comment by boy-hack** [comment]
可以
