### ISSUE TITLE
AttributeError: module 'gradio' has no attribute 'ClearButton'

### ISSUE THREAD

**Issue by 895515845** [Clouditera/secgpt#2]
运行提示AttributeError: module 'gradio' has no attribute 'ClearButton' 是gradio版本问题吗？我当前的版本是3.34.0，尝试更换低版本的gradio提示ImportError: cannot import name 'Random' from 'Crypto'

**Comment by boy-hack** [comment]
已添加依赖项
```
datasets==2.12.0
gradio==3.37.0
matplotlib==3.7.2
numpy==1.24.4
peft==0.5.0
torch==2.0.1
tqdm==4.65.0
transformers==4.32.0
```

**Comment by wuheuu** [comment]
@boy-hack 请问pypi上现在没有gradio 3.37.0了，是可以直接下载4.0.0之后的版本吗？https://pypi.org/project/gradio/#history
<img width="1502" alt="image" src="https://github.com/Clouditera/secgpt/assets/106037096/32b1e1fe-fa19-480b-b108-01c9a3c9a4a3">
<img width="789" alt="image" src="https://github.com/Clouditera/secgpt/assets/106037096/2b4162c0-4f47-4a41-ac50-7e57d5c3d9f3">
