### ISSUE TITLE
预训练问题

### ISSUE THREAD

**Issue by Duperr** [Clouditera/SecGPT#28]
想要针对secgpt做具体任务的预训练大概需要什么级别的显卡啊？

**Comment by ajunkguy** [comment]
预训练数据json地址可用吗？跑不通预训练，求助

**Comment by Duperr** [comment]
没整过呢，打算搞一下但不知道需要什么级别的显卡呢=-=

**Comment by boy-hack** [comment]
secgpt-mini 4090就够了
secgpt需要8*A100
