### ISSUE TITLE
关于数据集的问题

### ISSUE THREAD

**Issue by Dojay6103** [Clouditera/secgpt#3]
请问有监督数据集开源了吗？另外您开源的数据集到预训练数据的格式是如何转化的？

**Comment by boy-hack** [comment]
可以具体看脚本 https://github.com/Clouditera/secgpt/blob/main/dataset/pretrain.py

**Comment by Dojay6103** [comment]
感谢您的回复，我将您开源的.parquet数据集转化为json后只有text和对应类别，我理解这是对模型无监督的训练数据，想学习一下监督数据的生成方法和思路，不知道这个技术能否分享或指导？

**Comment by boy-hack** [comment]
开源的是无监督数据集，有监督数据集参考的是Alpaca instruction格式，目前自己的sft数据集比较少，暂未开源

**Comment by Sundogs8603** [comment]
您好，有计划开源这部分数据集么，或者有无数据集生成方法和思路呢

**Comment by boy-hack** [comment]
> 您好，有计划开源这部分数据集么，或者有无数据集生成方法和思路呢

可以利用GPT4对预训练中的数据进行清洗
