### ISSUE TITLE
关于预训练数据集的问题

### ISSUE THREAD

**Issue by yanjiachao2012** [Clouditera/SecGPT#58]
看到官方开源了数据集，但是是Parquet格式的，直接引用了数据集，会直接报错，是在用之前需要转一下格式吗

<img width="799" alt="image" src="https://github.com/Clouditera/SecGPT/assets/10867638/8e4dfb25-7615-4c15-85b3-31f5270cf67e">

<img width="943" alt="image" src="https://github.com/Clouditera/SecGPT/assets/10867638/b943974e-637e-44b2-b6c6-3a29bc4ade47">

**Comment by goodmaney** [comment]
他给的数据集是大数据专用存储格式，应该要调用特定包。

**Comment by yanjiachao2012** [comment]
嗯嗯，是要pandas处理一下
